apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  ports:
  - name: http
    port: 1200
    protocol: TCP
    targetPort: 80
  selector:
    app: netflix-app
  type: LoadBalancer
